export const TABS = {
  designer: 0,
  catalog: 1,
  pricing: 2,
  projects: 3,
  customers: 4,
};

export const fallbackTemplates = [
  { id: "template-linear-300", name: "Düz mutfak 300 cm", type: "linear" },
  { id: "template-l-360-240", name: "L mutfak 360 x 240 cm", type: "l_shape" },
  { id: "template-island-420", name: "Ada mutfak 420 cm", type: "island" },
];

const lightweightAsset = (name) => ({
  image_url: `/images/kitchen/products/lightweight/${name}.png`,
  model_url: `/models/kitchen/products/lightweight/${name}.glb`,
  source: "Kenney Furniture Kit CC0 GLB",
});

const flatBaseAsset = (name) => ({
  image_url: `/images/kitchen/products/lightweight/${name}.svg`,
  model_url: `/models/kitchen/products/lightweight/${name}.glb`,
  source: "Çıkıntısız GLB alt dolap",
});

const cabinetConstraints = (minWidth, maxWidth, minHeight = 60, maxHeight = 96) => ({
  min_width: minWidth,
  max_width: maxWidth,
  min_height: minHeight,
  max_height: maxHeight,
});

export const fallbackCatalog = [
  {
    id: "product-001-base-door-60",
    sku: "ALT-KPK-60",
    name: "Alt dolap - Tek kapaklı 60 cm",
    category: "base_cabinet",
    subcategory: "base_door",
    dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
    constraints: cabinetConstraints(45, 100),
    ...flatBaseAsset("flatBaseDoor"),
    base_price: 4800,
  },
  {
    id: "product-002-base-door-80",
    sku: "ALT-KPK-80",
    name: "Alt dolap - Çift kapaklı 80 cm",
    category: "base_cabinet",
    subcategory: "base_door",
    dimensions: { width: 80, height: 72, depth: 56, unit: "cm" },
    constraints: cabinetConstraints(60, 120),
    ...flatBaseAsset("flatBaseDoorDouble"),
    base_price: 5400,
  },
  {
    id: "product-003-base-drawer-60",
    sku: "ALT-CKM-60",
    name: "Alt dolap - Üç çekmeceli 60 cm",
    category: "base_cabinet",
    subcategory: "base_drawer",
    dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
    constraints: cabinetConstraints(45, 110),
    ...flatBaseAsset("flatBaseDrawer"),
    base_price: 6200,
  },
  {
    id: "product-004-base-drawer-90",
    sku: "ALT-CKM-90",
    name: "Alt dolap - Geniş çekmeceli 90 cm",
    category: "base_cabinet",
    subcategory: "base_drawer",
    dimensions: { width: 90, height: 72, depth: 56, unit: "cm" },
    constraints: cabinetConstraints(70, 140),
    ...flatBaseAsset("flatBaseDrawerWide"),
    base_price: 7100,
  },
  {
    id: "product-005-base-corner-90",
    sku: "ALT-KOSE-90",
    name: "Alt dolap - Köşe modülü 90 cm",
    category: "base_cabinet",
    subcategory: "base_corner",
    dimensions: { width: 90, height: 72, depth: 60, unit: "cm" },
    constraints: cabinetConstraints(80, 120),
    ...flatBaseAsset("flatBaseCorner"),
    base_price: 7800,
  },
  {
    id: "product-006-base-corner-drawer",
    sku: "ALT-KOSE-CKM",
    name: "Alt dolap - Köşe çekmeceli modül",
    category: "base_cabinet",
    subcategory: "base_corner",
    dimensions: { width: 100, height: 72, depth: 60, unit: "cm" },
    constraints: cabinetConstraints(80, 140),
    ...flatBaseAsset("flatBaseCornerDrawer"),
    base_price: 8600,
  },
  {
    id: "product-007-base-glass-60",
    sku: "ALT-CAM-60",
    name: "Alt dolap - Camlı vitrin 60 cm",
    category: "base_cabinet",
    subcategory: "base_glass",
    dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
    constraints: cabinetConstraints(45, 100),
    ...flatBaseAsset("flatBaseGlass"),
    base_price: 6900,
  },
  {
    id: "product-008-base-glass-80",
    sku: "ALT-CAM-80",
    name: "Alt dolap - Camlı çift kapak 80 cm",
    category: "base_cabinet",
    subcategory: "base_glass",
    dimensions: { width: 80, height: 72, depth: 56, unit: "cm" },
    constraints: cabinetConstraints(60, 120),
    ...flatBaseAsset("flatBaseGlassDouble"),
    base_price: 7600,
  },
  {
    id: "product-009-base-handleless-80",
    sku: "ALT-KULPSUZ-80",
    name: "Alt dolap - Kulpsuz lake 80 cm",
    category: "base_cabinet",
    subcategory: "base_handleless",
    dimensions: { width: 80, height: 72, depth: 56, unit: "cm" },
    constraints: cabinetConstraints(60, 130),
    ...flatBaseAsset("flatBaseHandleless"),
    base_price: 7200,
  },
  {
    id: "product-010-base-handleless-drawer",
    sku: "ALT-KULPSUZ-CKM",
    name: "Alt dolap - Kulpsuz çekmeceli modül",
    category: "base_cabinet",
    subcategory: "base_handleless",
    dimensions: { width: 100, height: 72, depth: 56, unit: "cm" },
    constraints: cabinetConstraints(70, 150),
    ...flatBaseAsset("flatBaseHandlelessDrawer"),
    base_price: 8400,
  },
  {
    id: "product-011-wall-solid-60",
    sku: "UST-KPK-60",
    name: "Üst dolap - Tek kapaklı 60 cm",
    category: "wall_cabinet",
    subcategory: "wall_solid",
    dimensions: { width: 60, height: 72, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(45, 100, 45, 110),
    ...lightweightAsset("kitchenCabinetUpper"),
    base_price: 3900,
  },
  {
    id: "product-012-wall-solid-80",
    sku: "UST-KPK-80",
    name: "Üst dolap - Çift kapaklı 80 cm",
    category: "wall_cabinet",
    subcategory: "wall_solid",
    dimensions: { width: 80, height: 72, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(60, 130, 45, 110),
    ...lightweightAsset("kitchenCabinetUpperDouble"),
    base_price: 5200,
  },
  {
    id: "product-013-wall-glass-60",
    sku: "UST-CAM-60",
    name: "Üst dolap - Camlı 60 cm",
    category: "wall_cabinet",
    subcategory: "wall_glass",
    dimensions: { width: 60, height: 72, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(45, 100, 45, 110),
    ...lightweightAsset("kitchenCabinetUpper"),
    base_price: 5600,
  },
  {
    id: "product-014-wall-glass-90",
    sku: "UST-CAM-90",
    name: "Üst dolap - Camlı geniş modül",
    category: "wall_cabinet",
    subcategory: "wall_glass",
    dimensions: { width: 90, height: 72, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(70, 140, 45, 110),
    ...lightweightAsset("kitchenCabinetUpperDouble"),
    base_price: 6800,
  },
  {
    id: "product-015-wall-lift-80",
    sku: "UST-LIFT-80",
    name: "Üst dolap - Lift kapak 80 cm",
    category: "wall_cabinet",
    subcategory: "wall_lift",
    dimensions: { width: 80, height: 45, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(60, 140, 36, 72),
    ...lightweightAsset("kitchenCabinetUpperLow"),
    base_price: 6100,
  },
  {
    id: "product-016-wall-lift-100",
    sku: "UST-LIFT-100",
    name: "Üst dolap - Yatay lift 100 cm",
    category: "wall_cabinet",
    subcategory: "wall_lift",
    dimensions: { width: 100, height: 45, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(80, 160, 36, 72),
    ...lightweightAsset("kitchenCabinetUpperLow"),
    base_price: 7400,
  },
  {
    id: "product-017-wall-corner-60",
    sku: "UST-KOSE-60",
    name: "Üst dolap - Köşe modülü",
    category: "wall_cabinet",
    subcategory: "wall_corner",
    dimensions: { width: 60, height: 72, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(50, 100, 45, 110),
    ...lightweightAsset("kitchenCabinetUpperCorner"),
    base_price: 5700,
  },
  {
    id: "product-018-wall-corner-wide",
    sku: "UST-KOSE-GEN",
    name: "Üst dolap - Geniş köşe modülü",
    category: "wall_cabinet",
    subcategory: "wall_corner",
    dimensions: { width: 80, height: 72, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(60, 120, 45, 110),
    ...lightweightAsset("kitchenCabinetUpperCorner"),
    base_price: 6900,
  },
  {
    id: "product-019-wall-open-60",
    sku: "UST-ACIK-60",
    name: "Üst dolap - Açık raflı 60 cm",
    category: "wall_cabinet",
    subcategory: "wall_open",
    dimensions: { width: 60, height: 72, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(45, 100, 45, 110),
    ...lightweightAsset("kitchenCabinetUpper"),
    base_price: 4300,
  },
  {
    id: "product-020-wall-open-90",
    sku: "UST-ACIK-90",
    name: "Üst dolap - Açık raflı geniş modül",
    category: "wall_cabinet",
    subcategory: "wall_open",
    dimensions: { width: 90, height: 72, depth: 34, unit: "cm" },
    constraints: cabinetConstraints(70, 140, 45, 110),
    ...lightweightAsset("kitchenCabinetUpperDouble"),
    base_price: 5900,
  },
  {
    id: "product-021-counter-straight",
    sku: "TEZ-DUZ-180",
    name: "Tezgah - Düz tabla 180 cm",
    category: "countertop",
    subcategory: "countertop_straight",
    dimensions: { width: 180, height: 4, depth: 60, unit: "cm" },
    constraints: cabinetConstraints(120, 320, 3, 8),
    ...lightweightAsset("kitchenBar"),
    base_price: 7200,
  },
  {
    id: "product-022-counter-end",
    sku: "TEZ-BIT-90",
    name: "Tezgah - Bitiş modülü 90 cm",
    category: "countertop",
    subcategory: "countertop_straight",
    dimensions: { width: 90, height: 4, depth: 60, unit: "cm" },
    constraints: cabinetConstraints(60, 180, 3, 8),
    ...lightweightAsset("kitchenBarEnd"),
    base_price: 5400,
  },
  {
    id: "product-023-sink-single",
    sku: "EVYE-TEK-60",
    name: "Lavabo / evye - Tek hazneli",
    category: "sink",
    subcategory: "sink_modules",
    dimensions: { width: 60, height: 12, depth: 45, unit: "cm" },
    constraints: cabinetConstraints(45, 90, 8, 24),
    ...lightweightAsset("kitchenSink"),
    base_price: 3600,
  },
  {
    id: "product-024-sink-square",
    sku: "EVYE-KARE-45",
    name: "Lavabo / evye - Kare hazne",
    category: "sink",
    subcategory: "sink_modules",
    dimensions: { width: 45, height: 12, depth: 45, unit: "cm" },
    constraints: cabinetConstraints(40, 80, 8, 24),
    ...lightweightAsset("bathroomSinkSquare"),
    base_price: 3100,
  },
  {
    id: "product-025-cooktop-electric",
    sku: "OCAK-ELEK-60",
    name: "Set üstü ocak - Elektrikli",
    category: "cooktop",
    subcategory: "cooktop_modules",
    dimensions: { width: 60, height: 8, depth: 52, unit: "cm" },
    constraints: cabinetConstraints(45, 90, 5, 18),
    ...lightweightAsset("kitchenStoveElectric"),
    base_price: 6800,
  },
  {
    id: "product-026-cooktop-range",
    sku: "OCAK-MOD-60",
    name: "Set üstü ocak - Fırınlı görünüm",
    category: "cooktop",
    subcategory: "cooktop_modules",
    dimensions: { width: 60, height: 10, depth: 52, unit: "cm" },
    constraints: cabinetConstraints(45, 90, 5, 24),
    ...lightweightAsset("kitchenStove"),
    base_price: 7900,
  },
];

export const fallbackMaterials = [
  {
    id: "mat-door-lake-white",
    code: "LAKE-WHITE",
    name: "Beyaz lake kapak",
    type: "door",
    color_hex: "#F8FAFC",
    price_modifier: 0.18,
    modifier_type: "percent",
  },
  {
    id: "mat-door-wood-oak",
    code: "WOOD-OAK",
    name: "Meşe kapak",
    type: "door",
    color_hex: "#B6814A",
    price_modifier: 0.12,
    modifier_type: "percent",
  },
  {
    id: "mat-door-anthracite",
    code: "MAT-ANT",
    name: "Antrasit mat kapak",
    type: "door",
    color_hex: "#374151",
    price_modifier: 0.1,
    modifier_type: "percent",
  },
  {
    id: "mat-door-sage",
    code: "SAGE-GREEN",
    name: "Ada çayı yeşili kapak",
    type: "door",
    color_hex: "#8FAF9B",
    price_modifier: 0.14,
    modifier_type: "percent",
  },
  {
    id: "mat-door-navy",
    code: "NAVY-SATIN",
    name: "Lacivert saten kapak",
    type: "door",
    color_hex: "#1E3A5F",
    price_modifier: 0.16,
    modifier_type: "percent",
  },
  {
    id: "mat-glass-smoked",
    code: "GLASS-SMOKE",
    name: "Füme cam",
    type: "glass",
    color_hex: "#6B7280",
    price_modifier: 900,
    modifier_type: "fixed",
  },
  {
    id: "mat-glass-clear",
    code: "GLASS-CLEAR",
    name: "Şeffaf cam",
    type: "glass",
    color_hex: "#BAE6FD",
    price_modifier: 650,
    modifier_type: "fixed",
  },
  {
    id: "mat-glass-fluted",
    code: "GLASS-FLUTED",
    name: "Fitilli cam",
    type: "glass",
    color_hex: "#CBD5E1",
    price_modifier: 1200,
    modifier_type: "fixed",
  },
  {
    id: "mat-counter-quartz",
    code: "QUARTZ",
    name: "Kuvars tezgah",
    type: "countertop",
    color_hex: "#E5E7EB",
    price_modifier: 0.32,
    modifier_type: "percent",
  },
  {
    id: "mat-counter-wood",
    code: "WOOD-TOP",
    name: "Ahşap tezgah",
    type: "countertop",
    color_hex: "#9A6A3A",
    price_modifier: 0.18,
    modifier_type: "percent",
  },
  {
    id: "mat-counter-black",
    code: "BLACK-GRANITE",
    name: "Siyah granit tezgah",
    type: "countertop",
    color_hex: "#111827",
    price_modifier: 0.42,
    modifier_type: "percent",
  },
];

export const templateScenes = {
  "template-linear-300": [
    {
      catalog_item_id: "product-001-base-door-60",
      position: { x: 130, y: 320, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-lake-white" },
      quantity: 1,
    },
    {
      catalog_item_id: "product-003-base-drawer-60",
      position: { x: 200, y: 320, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-wood-oak" },
      quantity: 1,
    },
    {
      catalog_item_id: "product-011-wall-solid-60",
      position: { x: 145, y: 140, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 60, height: 72, depth: 34, unit: "cm" },
      options: { door_material_id: "mat-door-lake-white" },
      quantity: 1,
    },
  ],
  "template-l-360-240": [
    {
      catalog_item_id: "product-002-base-door-80",
      position: { x: 120, y: 320, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 80, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-lake-white" },
      quantity: 1,
    },
    {
      catalog_item_id: "product-014-wall-glass-90",
      position: { x: 130, y: 140, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 90, height: 72, depth: 34, unit: "cm" },
      options: {
        door_material_id: "mat-door-anthracite",
        glass_material_id: "mat-glass-smoked",
      },
      quantity: 1,
    },
  ],
  "template-island-420": [
    {
      catalog_item_id: "product-004-base-drawer-90",
      position: { x: 150, y: 305, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 90, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-wood-oak" },
      quantity: 1,
    },
    {
      catalog_item_id: "product-021-counter-straight",
      position: { x: 135, y: 280, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 180, height: 4, depth: 60, unit: "cm" },
      options: { countertop_material_id: "mat-counter-quartz" },
      quantity: 1,
    },
    {
      catalog_item_id: "product-023-sink-single",
      position: { x: 190, y: 265, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 60, height: 12, depth: 45, unit: "cm" },
      options: {},
      quantity: 1,
    },
  ],
};

export const catalogGroups = [
  {
    key: "base_cabinet",
    title: "Alt Dolaplar",
    subcategories: [
      { key: "base_door", title: "Kapaklı Alt Dolaplar" },
      { key: "base_drawer", title: "Çekmeceli Alt Dolaplar" },
      { key: "base_corner", title: "Köşe Alt Dolaplar" },
      { key: "base_glass", title: "Camlı Alt Dolaplar" },
      { key: "base_handleless", title: "Kulpsuz Alt Dolaplar" },
    ],
  },
  {
    key: "wall_cabinet",
    title: "Üst Dolaplar",
    subcategories: [
      { key: "wall_solid", title: "Kapaklı Üst Dolaplar" },
      { key: "wall_glass", title: "Camlı Üst Dolaplar" },
      { key: "wall_lift", title: "Lift Üst Dolaplar" },
      { key: "wall_corner", title: "Köşe Üst Dolaplar" },
      { key: "wall_open", title: "Açık Raflı Üst Dolaplar" },
    ],
  },
  {
    key: "countertop",
    title: "Tezgahlar",
    subcategories: [{ key: "countertop_straight", title: "Tezgah Modülleri" }],
  },
  {
    key: "sink",
    title: "Lavabo / Evye",
    subcategories: [{ key: "sink_modules", title: "Evye Modülleri" }],
  },
  {
    key: "cooktop",
    title: "Set Üstü Ocak",
    subcategories: [{ key: "cooktop_modules", title: "Ocak Modülleri" }],
  },
];
