export const TABS = {
  designer: 0,
  catalog: 1,
  pricing: 2,
  projects: 3,
  customers: 4,
};

export const fallbackTemplates = [
  { id: "template-linear-300", name: "Duz mutfak 300 cm", type: "linear" },
  { id: "template-l-360-240", name: "L mutfak 360 x 240 cm", type: "l_shape" },
  { id: "template-island-420", name: "Ada mutfak 420 cm", type: "island" },
];

export const fallbackCatalog = [
  {
    id: "cabinet-base-60",
    sku: "ALT-060",
    name: "Alt dolap 60 cm",
    category: "base_cabinet",
    dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
    constraints: {
      min_width: 40,
      max_width: 90,
      min_height: 60,
      max_height: 90,
    },
    image_url: "/images/kitchen/base-cabinet-premium.svg",
    model_url: "/models/kitchen/base-cabinet-premium.gltf",
    base_price: 4800,
  },
  {
    id: "cabinet-base-80-drawer",
    sku: "ALT-080-CKM",
    name: "Cekmeceli alt dolap 80 cm",
    category: "base_cabinet",
    dimensions: { width: 80, height: 72, depth: 56, unit: "cm" },
    constraints: {
      min_width: 60,
      max_width: 120,
      min_height: 60,
      max_height: 90,
    },
    image_url: "/images/kitchen/base-cabinet-drawer-premium.svg",
    model_url: "/models/kitchen/base-cabinet-drawer-premium.gltf",
    base_price: 6900,
  },
  {
    id: "cabinet-base-corner",
    sku: "ALT-KOSE",
    name: "Kose alt dolap",
    category: "base_cabinet",
    dimensions: { width: 90, height: 72, depth: 90, unit: "cm" },
    constraints: {
      min_width: 80,
      max_width: 120,
      min_height: 60,
      max_height: 90,
    },
    image_url: "/images/kitchen/island-cabinet-premium.svg",
    model_url: "/models/kitchen/island-cabinet-premium.gltf",
    base_price: 8200,
  },
  {
    id: "cabinet-tall-60",
    sku: "BOY-060",
    name: "Boy dolabi 60 cm",
    category: "base_cabinet",
    dimensions: { width: 60, height: 210, depth: 58, unit: "cm" },
    constraints: {
      min_width: 45,
      max_width: 80,
      min_height: 180,
      max_height: 240,
    },
    image_url: "/images/kitchen/tall-pantry-premium.svg",
    model_url: "/models/kitchen/tall-pantry-premium.gltf",
    base_price: 11200,
  },
  {
    id: "cabinet-wall-80",
    sku: "UST-080",
    name: "Ust dolap 80 cm",
    category: "wall_cabinet",
    dimensions: { width: 80, height: 72, depth: 34, unit: "cm" },
    constraints: {
      min_width: 50,
      max_width: 120,
      min_height: 45,
      max_height: 100,
    },
    image_url: "/images/kitchen/wall-cabinet-left-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-left-premium.gltf",
    base_price: 3900,
  },
  {
    id: "cabinet-wall-60-glass",
    sku: "UST-060-CAM",
    name: "Camli ust dolap 60 cm",
    category: "wall_cabinet",
    dimensions: { width: 60, height: 72, depth: 34, unit: "cm" },
    constraints: {
      min_width: 45,
      max_width: 90,
      min_height: 45,
      max_height: 100,
    },
    image_url: "/images/kitchen/wall-cabinet-glass-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-glass-premium.gltf",
    base_price: 4600,
  },
  {
    id: "cabinet-wall-100",
    sku: "UST-100",
    name: "Ust dolap 100 cm",
    category: "wall_cabinet",
    dimensions: { width: 100, height: 72, depth: 34, unit: "cm" },
    constraints: {
      min_width: 70,
      max_width: 140,
      min_height: 45,
      max_height: 100,
    },
    image_url: "/images/kitchen/wall-cabinet-long-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-long-premium.gltf",
    base_price: 5200,
  },
  {
    id: "cabinet-wall-corner",
    sku: "UST-KOSE",
    name: "Kose ust dolap",
    category: "wall_cabinet",
    dimensions: { width: 68, height: 72, depth: 68, unit: "cm" },
    constraints: {
      min_width: 60,
      max_width: 100,
      min_height: 45,
      max_height: 100,
    },
    image_url: "/images/kitchen/wall-cabinet-corner-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-corner-premium.gltf",
    base_price: 5700,
  },
  {
    id: "countertop-meter",
    sku: "TEZ-MT",
    name: "Tezgah metre",
    category: "countertop",
    dimensions: { width: 100, height: 4, depth: 60, unit: "cm" },
    constraints: {
      min_width: 60,
      max_width: 420,
      min_height: 3,
      max_height: 12,
    },
    image_url: "/images/kitchen/countertop-stone-premium.svg",
    model_url: "/models/kitchen/countertop-stone-premium.gltf",
    base_price: 2200,
  },
  {
    id: "countertop-long-240",
    sku: "TEZ-DUZ-240",
    name: "Uzun duz tezgah 240 cm",
    category: "countertop",
    dimensions: { width: 240, height: 10, depth: 64, unit: "cm" },
    constraints: {
      min_width: 120,
      max_width: 420,
      min_height: 6,
      max_height: 16,
    },
    image_url: "/images/kitchen/countertop-long-slab-premium.svg",
    model_url: "/models/kitchen/countertop-long-slab-premium.gltf",
    base_price: 5200,
  },
  {
    id: "countertop-l-corner",
    sku: "TEZ-L-KOSE",
    name: "L kose tezgah",
    category: "countertop",
    dimensions: { width: 220, height: 12, depth: 140, unit: "cm" },
    constraints: {
      min_width: 140,
      max_width: 360,
      min_height: 6,
      max_height: 18,
    },
    image_url: "/images/kitchen/countertop-l-slab-premium.svg",
    model_url: "/models/kitchen/countertop-l-slab-premium.gltf",
    base_price: 7600,
  },
  {
    id: "countertop-sink-integrated",
    sku: "TEZ-EVYELI",
    name: "Evyeli tezgah modulu",
    category: "countertop",
    dimensions: { width: 160, height: 14, depth: 64, unit: "cm" },
    constraints: {
      min_width: 120,
      max_width: 260,
      min_height: 8,
      max_height: 20,
    },
    image_url: "/images/kitchen/countertop-sink-cut-premium.svg",
    model_url: "/models/kitchen/countertop-sink-cut-premium.gltf",
    base_price: 8400,
  },
  {
    id: "sink-standard",
    sku: "EVY-STD",
    name: "Standart evye",
    category: "appliance",
    dimensions: { width: 50, height: 20, depth: 45, unit: "cm" },
    constraints: {
      min_width: 45,
      max_width: 70,
      min_height: 15,
      max_height: 35,
    },
    image_url: "/images/kitchen/sink-steel-premium.svg",
    model_url: "/models/kitchen/sink-steel-premium.gltf",
    base_price: 3200,
  },
  {
    id: "cooktop-built-in",
    sku: "OCAK-ANK",
    name: "Ankastre siyah ocak",
    category: "appliance",
    dimensions: { width: 60, height: 8, depth: 50, unit: "cm" },
    constraints: {
      min_width: 50,
      max_width: 80,
      min_height: 5,
      max_height: 14,
    },
    image_url: "/images/kitchen/cooktop-black-premium.svg",
    model_url: "/models/kitchen/cooktop-black-premium.gltf",
    base_price: 6100,
  },
  {
    id: "faucet-chrome",
    sku: "BAT-KROM",
    name: "Krom mutfak bataryasi",
    category: "appliance",
    dimensions: { width: 24, height: 42, depth: 22, unit: "cm" },
    constraints: {
      min_width: 16,
      max_width: 40,
      min_height: 28,
      max_height: 60,
    },
    image_url: "/images/kitchen/faucet-chrome-premium.svg",
    model_url: "/models/kitchen/faucet-chrome-premium.gltf",
    base_price: 2400,
  },
  {
    id: "shelf-inner-60",
    sku: "RAF-060",
    name: "Ic raf 60 cm",
    category: "shelf",
    dimensions: { width: 56, height: 3, depth: 50, unit: "cm" },
    constraints: { min_width: 30, max_width: 90, min_height: 2, max_height: 8 },
    image_url: "/images/kitchen/open-shelf-premium.svg",
    model_url: "/models/kitchen/open-shelf-premium.gltf",
    base_price: 650,
  },
  {
    id: "kitchen-room-demo",
    sku: "MUTFAK-DUZ-360",
    name: "Duz hazir mutfak modeli",
    category: "room",
    dimensions: { width: 360, height: 240, depth: 220, unit: "cm" },
    constraints: {
      min_width: 280,
      max_width: 520,
      min_height: 220,
      max_height: 320,
    },
    image_url: "/images/kitchen/kitchen-layout-linear-premium.svg",
    model_url: "/models/kitchen/kitchen-layout-linear-premium.gltf",
    source: "OpenGameArt Tiny Treats CC0 + Decusin demo composition",
    base_price: 0,
  },
  {
    id: "kitchen-room-l-premium",
    sku: "MUTFAK-L-360",
    name: "L hazir mutfak modeli",
    category: "room",
    dimensions: { width: 360, height: 240, depth: 240, unit: "cm" },
    constraints: {
      min_width: 300,
      max_width: 560,
      min_height: 220,
      max_height: 320,
    },
    image_url: "/images/kitchen/kitchen-layout-l-premium.svg",
    model_url: "/models/kitchen/kitchen-layout-l-premium.gltf",
    source: "OpenGameArt Tiny Treats CC0 + Decusin demo composition",
    base_price: 0,
  },
  {
    id: "kitchen-room-island-premium",
    sku: "MUTFAK-ADA-420",
    name: "Ada hazir mutfak modeli",
    category: "room",
    dimensions: { width: 420, height: 240, depth: 260, unit: "cm" },
    constraints: {
      min_width: 340,
      max_width: 620,
      min_height: 220,
      max_height: 320,
    },
    image_url: "/images/kitchen/kitchen-layout-island-premium.svg",
    model_url: "/models/kitchen/kitchen-layout-island-premium.gltf",
    source: "OpenGameArt Tiny Treats CC0 + Decusin demo composition",
    base_price: 0,
  },
  {
    id: "shelf-spice-30",
    sku: "RAF-BAH-030",
    name: "Baharat rafı 30 cm",
    category: "shelf",
    dimensions: { width: 30, height: 60, depth: 18, unit: "cm" },
    constraints: {
      min_width: 20,
      max_width: 50,
      min_height: 40,
      max_height: 90,
    },
    image_url: "/images/kitchen/open-shelf-premium.svg",
    model_url: "/models/kitchen/open-shelf-premium.gltf",
    base_price: 1250,
  },
  {
    id: "cabinet-base-100-premium",
    sku: "ALT-100-PRM",
    name: "Premium alt dolap 100 cm",
    category: "base_cabinet",
    dimensions: { width: 100, height: 72, depth: 56, unit: "cm" },
    constraints: {
      min_width: 70,
      max_width: 140,
      min_height: 60,
      max_height: 90,
    },
    image_url: "/images/kitchen/base-cabinet-premium.svg",
    model_url: "/models/kitchen/base-cabinet-premium.gltf",
    base_price: 7800,
  },
  {
    id: "cabinet-base-120-drawer",
    sku: "ALT-120-CKM",
    name: "Genis cekmeceli alt dolap",
    category: "base_cabinet",
    dimensions: { width: 120, height: 72, depth: 56, unit: "cm" },
    constraints: {
      min_width: 80,
      max_width: 160,
      min_height: 60,
      max_height: 90,
    },
    image_url: "/images/kitchen/base-cabinet-drawer-premium.svg",
    model_url: "/models/kitchen/base-cabinet-drawer-premium.gltf",
    base_price: 9600,
  },
  {
    id: "cabinet-base-dark-80",
    sku: "ALT-080-DARK",
    name: "Antrasit alt dolap 80 cm",
    category: "base_cabinet",
    dimensions: { width: 80, height: 72, depth: 56, unit: "cm" },
    constraints: {
      min_width: 60,
      max_width: 120,
      min_height: 60,
      max_height: 90,
    },
    image_url: "/images/kitchen/base-cabinet-premium.svg",
    model_url: "/models/kitchen/base-cabinet-premium.gltf",
    base_price: 7400,
  },
  {
    id: "cabinet-island-180",
    sku: "ADA-180",
    name: "Ada modul 180 cm",
    category: "base_cabinet",
    dimensions: { width: 180, height: 88, depth: 90, unit: "cm" },
    constraints: {
      min_width: 140,
      max_width: 260,
      min_height: 80,
      max_height: 95,
    },
    image_url: "/images/kitchen/island-cabinet-premium.svg",
    model_url: "/models/kitchen/island-cabinet-premium.gltf",
    base_price: 18500,
  },
  {
    id: "cabinet-wall-120-glass",
    sku: "UST-120-CAM",
    name: "Genis camli ust dolap",
    category: "wall_cabinet",
    dimensions: { width: 120, height: 72, depth: 34, unit: "cm" },
    constraints: {
      min_width: 80,
      max_width: 160,
      min_height: 45,
      max_height: 100,
    },
    image_url: "/images/kitchen/wall-cabinet-right-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-right-premium.gltf",
    base_price: 6800,
  },
  {
    id: "cabinet-wall-lift-90",
    sku: "UST-090-LIFT",
    name: "Lift kapak ust dolap",
    category: "wall_cabinet",
    dimensions: { width: 90, height: 48, depth: 34, unit: "cm" },
    constraints: {
      min_width: 70,
      max_width: 140,
      min_height: 36,
      max_height: 72,
    },
    image_url: "/images/kitchen/wall-cabinet-long-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-long-premium.gltf",
    base_price: 6100,
  },
  {
    id: "cabinet-wall-single-left-45",
    sku: "UST-045-SOL",
    name: "Sol tek kapak ust dolap",
    category: "wall_cabinet",
    dimensions: { width: 45, height: 72, depth: 34, unit: "cm" },
    constraints: {
      min_width: 35,
      max_width: 70,
      min_height: 45,
      max_height: 100,
    },
    image_url: "/images/kitchen/wall-cabinet-left-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-left-premium.gltf",
    base_price: 3600,
  },
  {
    id: "cabinet-wall-single-right-45",
    sku: "UST-045-SAG",
    name: "Sag tek kapak ust dolap",
    category: "wall_cabinet",
    dimensions: { width: 45, height: 72, depth: 34, unit: "cm" },
    constraints: {
      min_width: 35,
      max_width: 70,
      min_height: 45,
      max_height: 100,
    },
    image_url: "/images/kitchen/wall-cabinet-right-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-right-premium.gltf",
    base_price: 3600,
  },
  {
    id: "cabinet-wall-straight-140",
    sku: "UST-140-DUZ",
    name: "Uzun ust dolap modulu",
    category: "wall_cabinet",
    dimensions: { width: 140, height: 72, depth: 34, unit: "cm" },
    constraints: {
      min_width: 100,
      max_width: 180,
      min_height: 45,
      max_height: 100,
    },
    image_url: "/images/kitchen/wall-cabinet-long-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-long-premium.gltf",
    base_price: 7400,
  },
  {
    id: "cabinet-wall-corner-tiny",
    sku: "UST-KOSE-TINY",
    name: "Moduler kose ust dolap",
    category: "wall_cabinet",
    dimensions: { width: 72, height: 72, depth: 72, unit: "cm" },
    constraints: {
      min_width: 55,
      max_width: 110,
      min_height: 45,
      max_height: 100,
    },
    image_url: "/images/kitchen/wall-cabinet-corner-premium.svg",
    model_url: "/models/kitchen/wall-cabinet-corner-premium.gltf",
    base_price: 6200,
  },
  {
    id: "wall-open-shelf-hooks",
    sku: "UST-RAF-KANCALI",
    name: "Kancali acik ust raf",
    category: "shelf",
    dimensions: { width: 90, height: 40, depth: 24, unit: "cm" },
    constraints: {
      min_width: 60,
      max_width: 140,
      min_height: 25,
      max_height: 70,
    },
    image_url: "/images/kitchen/wall-shelf-hooks-premium.svg",
    model_url: "/models/kitchen/wall-shelf-hooks-premium.gltf",
    base_price: 2800,
  },
  {
    id: "wall-open-shelf-corner",
    sku: "UST-RAF-KOSE",
    name: "Kose acik ust raf",
    category: "shelf",
    dimensions: { width: 70, height: 42, depth: 42, unit: "cm" },
    constraints: {
      min_width: 50,
      max_width: 110,
      min_height: 25,
      max_height: 75,
    },
    image_url: "/images/kitchen/wall-shelf-corner-premium.svg",
    model_url: "/models/kitchen/wall-shelf-corner-premium.gltf",
    base_price: 3100,
  },
  {
    id: "sink-steel-large",
    sku: "EVY-XL-CELIK",
    name: "Buyuk celik evye",
    category: "appliance",
    dimensions: { width: 72, height: 22, depth: 50, unit: "cm" },
    constraints: {
      min_width: 55,
      max_width: 90,
      min_height: 15,
      max_height: 35,
    },
    image_url: "/images/kitchen/sink-steel-premium.svg",
    model_url: "/models/kitchen/sink-steel-premium.gltf",
    base_price: 5200,
  },
  {
    id: "shelf-open-120",
    sku: "RAF-ACIK-120",
    name: "Genis acik raf",
    category: "shelf",
    dimensions: { width: 120, height: 18, depth: 28, unit: "cm" },
    constraints: {
      min_width: 80,
      max_width: 180,
      min_height: 10,
      max_height: 35,
    },
    image_url: "/images/kitchen/open-shelf-premium.svg",
    model_url: "/models/kitchen/open-shelf-premium.gltf",
    base_price: 1950,
  },
];

export const fallbackMaterials = [
  {
    id: "mat-door-lake-white",
    code: "LAKE-WHITE",
    name: "Beyaz lake kapak",
    type: "door",
    color_hex: "#F8FAFC",
    preview_model_url: "/models/kitchen/base-cabinet-premium.gltf",
    price_modifier: 0.18,
    modifier_type: "percent",
  },
  {
    id: "mat-door-wood-oak",
    code: "WOOD-OAK",
    name: "Mese kapak",
    type: "door",
    color_hex: "#B6814A",
    price_modifier: 0.12,
    modifier_type: "percent",
  },
  {
    id: "mat-door-anthracite",
    code: "MAT-ANT",
    name: "Antrasit mat kapak",
    type: "door",
    color_hex: "#374151",
    price_modifier: 0.1,
    modifier_type: "percent",
  },
  {
    id: "mat-door-sage",
    code: "SAGE-GREEN",
    name: "Ada cayi yesili kapak",
    type: "door",
    color_hex: "#8FAF9B",
    price_modifier: 0.14,
    modifier_type: "percent",
  },
  {
    id: "mat-door-navy",
    code: "NAVY-SATIN",
    name: "Lacivert saten kapak",
    type: "door",
    color_hex: "#1E3A5F",
    price_modifier: 0.16,
    modifier_type: "percent",
  },
  {
    id: "mat-glass-smoked",
    code: "GLASS-SMOKE",
    name: "Fume cam",
    type: "glass",
    color_hex: "#6B7280",
    preview_model_url: "/models/kitchen/wall-cabinet-glass-premium.gltf",
    price_modifier: 900,
    modifier_type: "fixed",
  },
  {
    id: "mat-glass-clear",
    code: "GLASS-CLEAR",
    name: "Seffaf cam",
    type: "glass",
    color_hex: "#BAE6FD",
    price_modifier: 650,
    modifier_type: "fixed",
  },
  {
    id: "mat-glass-fluted",
    code: "GLASS-FLUTED",
    name: "Fitilli cam",
    type: "glass",
    color_hex: "#CBD5E1",
    price_modifier: 1200,
    modifier_type: "fixed",
  },
  {
    id: "mat-counter-quartz",
    code: "QUARTZ",
    name: "Kuvars tezgah",
    type: "countertop",
    color_hex: "#E5E7EB",
    preview_model_url: "/models/kitchen/countertop-stone-premium.gltf",
    price_modifier: 0.32,
    modifier_type: "percent",
  },
  {
    id: "mat-counter-wood",
    code: "WOOD-TOP",
    name: "Ahsap tezgah",
    type: "countertop",
    color_hex: "#9A6A3A",
    price_modifier: 0.18,
    modifier_type: "percent",
  },
  {
    id: "mat-counter-black",
    code: "BLACK-GRANITE",
    name: "Siyah granit tezgah",
    type: "countertop",
    color_hex: "#111827",
    price_modifier: 0.42,
    modifier_type: "percent",
  },
];

export const templateScenes = {
  "template-linear-300": [
    {
      catalog_item_id: "cabinet-base-60",
      position: { x: 130, y: 320, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-lake-white" },
      quantity: 1,
    },
    {
      catalog_item_id: "cabinet-base-60",
      position: { x: 200, y: 320, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-lake-white" },
      quantity: 1,
    },
    {
      catalog_item_id: "cabinet-wall-80",
      position: { x: 145, y: 140, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 80, height: 72, depth: 34, unit: "cm" },
      options: {
        door_material_id: "mat-door-lake-white",
        glass_material_id: "mat-glass-smoked",
      },
      quantity: 1,
    },
  ],
  "template-l-360-240": [
    {
      catalog_item_id: "cabinet-base-60",
      position: { x: 120, y: 320, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-lake-white" },
      quantity: 1,
    },
    {
      catalog_item_id: "cabinet-base-60",
      position: { x: 188, y: 320, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 60, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-lake-white" },
      quantity: 1,
    },
    {
      catalog_item_id: "cabinet-wall-80",
      position: { x: 130, y: 140, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 80, height: 72, depth: 34, unit: "cm" },
      options: {
        door_material_id: "mat-door-lake-white",
        glass_material_id: "mat-glass-smoked",
      },
      quantity: 1,
    },
    {
      catalog_item_id: "cabinet-wall-80",
      position: { x: 300, y: 220, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 80, height: 72, depth: 34, unit: "cm" },
      options: {
        door_material_id: "mat-door-wood-oak",
        glass_material_id: "mat-glass-smoked",
      },
      quantity: 1,
    },
  ],
  "template-island-420": [
    {
      catalog_item_id: "cabinet-base-60",
      position: { x: 150, y: 305, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 80, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-wood-oak" },
      quantity: 1,
    },
    {
      catalog_item_id: "cabinet-base-60",
      position: { x: 245, y: 305, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 80, height: 72, depth: 56, unit: "cm" },
      options: { door_material_id: "mat-door-wood-oak" },
      quantity: 1,
    },
    {
      catalog_item_id: "countertop-meter",
      position: { x: 135, y: 280, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 210, height: 16, depth: 80, unit: "cm" },
      options: { countertop_material_id: "mat-counter-quartz" },
      quantity: 1,
    },
    {
      catalog_item_id: "sink-standard",
      position: { x: 390, y: 265, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      dimensions: { width: 60, height: 45, depth: 45, unit: "cm" },
      options: {},
      quantity: 1,
    },
  ],
};

export const catalogGroups = [
  { key: "base_cabinet", title: "Alt Dolaplar" },
  { key: "wall_cabinet", title: "Ust Dolaplar" },
  { key: "countertop", title: "Tezgahlar" },
  { key: "shelf", title: "Raflar" },
  { key: "appliance", title: "Evye / Cihazlar" },
  { key: "room", title: "Mutfak Modelleri" },
];
